# Generated by Django 2.1.2 on 2018-10-21 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opm', '0002_userdetails'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userdetails',
            table='userdetails',
        ),
    ]
