# Generated by Django 2.1.2 on 2018-11-01 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opm', '0003_auto_20181021_2231'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientMedicalHistory',
            fields=[
                ('patientid', models.ForeignKey(db_column='patientID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='opm.Patient')),
                ('bloodtype', models.CharField(db_column='bloodType', max_length=45)),
                ('presentcomplaint', models.TextField(db_column='presentComplaint')),
                ('historyofpresentcomplaint', models.TextField(db_column='historyOfPresentComplaint')),
                ('pastmedicalhistory', models.TextField(blank=True, db_column='pastMedicalHistory', null=True)),
                ('drughistory', models.TextField(blank=True, db_column='drugHistory', null=True)),
                ('familyhistory', models.TextField(blank=True, db_column='familyHistory', null=True)),
                ('socialhistory', models.TextField(blank=True, db_column='socialHistory', null=True)),
            ],
            options={
                'db_table': 'patient_medical_history',
                'managed': False,
            },
        ),
    ]
