# Generated by Django 2.1.2 on 2018-11-17 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opm', '0004_patientmedicalhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerts',
            fields=[
                ('alertid', models.AutoField(db_column='alertID', primary_key=True, serialize=False)),
                ('typeofvital', models.IntegerField(db_column='typeOfVital')),
                ('timestamp', models.DateTimeField()),
                ('viewed', models.IntegerField()),
            ],
            options={
                'db_table': 'alerts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Thresholds',
            fields=[
                ('thresholdsid', models.AutoField(db_column='thresholdsID', primary_key=True, serialize=False)),
                ('mintemperature', models.FloatField(db_column='minTemperature')),
                ('maxtemperature', models.FloatField(db_column='maxTemperature')),
                ('minheartrate', models.IntegerField(db_column='minHeartrate')),
                ('maxheartrate', models.IntegerField(db_column='maxHeartrate')),
            ],
            options={
                'db_table': 'thresholds',
                'managed': False,
            },
        ),
    ]
