# Generated by Django 2.1.2 on 2018-11-20 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opm', '0005_alerts_thresholds'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefTypeofvital',
            fields=[
                ('typeofvitalid', models.IntegerField(db_column='typeOfVitalID', primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'ref_typeofvital',
                'managed': False,
            },
        ),
    ]
