# Generated by Django 2.1.2 on 2018-11-22 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opm', '0006_reftypeofvital'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('commentid', models.IntegerField(db_column='commentID', primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'comments',
                'managed': False,
            },
        ),
    ]
