from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('loginuser/', views.loginuser, name='loginuser'),
    path('adminauthentication/', views.adminauthentication, name='adminauthentication'),
    path('adminauthenticate/<str:otp>', views.adminauthenticate, name='adminauthenticate'),
    path('home/', views.home, name='home'),
    path('notifications/', views.notifications, name='notifications'),
    path('listofusers/', views.listofusers, name='listofusers'),
    path('filloutmedicalform/', views.filloutmedicalform, name='filloutmedicalform'),
    path('createuser/', views.createuser, name='createuser'),
    path('changeuserofdevice/', views.changeuserofdevice, name='changeuserofdevice'),
    path('viewassignedpatients/', views.viewassignedpatients, name='viewassignedpatients'),
    path('managedevicerecording/', views.managedevicerecording, name='managedevicerecording'),
    path('viewcurrentvitals/', views.viewcurrentvitals, name='viewcurrentvitals'),
    path('viewhistoryofvitals/', views.viewhistoryofvitals, name='viewhistoryofvitals'),
    path('viewhistoryofvitals/<int:medical_history_id>/medicalform', views.viewhistoryofvitalsmediclaform, name='viewhistoryofvitalsmediclaform'),
    path('viewhistoryofvitals/<int:patientdevice_id>/<str:date>/vitalrecords', views.viewhistoryofvitalvitalrecords, name='viewhistoryofvitalvitalrecords'),
    path('restrictuseraccess/', views.restrictuseraccess, name='restrictuseraccess'),
    path('managedoctoraccount/', views.managedoctoraccount, name='managedoctoraccount'),
    path('managepatientaccount/', views.managepatientaccount, name='managepatientaccount'),
    path('viewassignedpatients/<int:patient_id>/vitals/', views.assignedpatientvitals, name='patientvitals'),
    path('viewassignedpatients/<int:patient_id>/medicalinfo/', views.assignedpatientmedicalinfo, name='patientmedicalinfo'),
    path('viewassignedpatients/<int:patient_id>/records/', views.assignedpatientrecords, name='patientrecords'),
    path('viewassignedpatients/<int:patient_id>/records/<int:medical_history_id>/medicalform', views.assignedpatientrecordsmedicalhistory, name='assignedpatientrecordsmedicalhistory'),
    path('viewassignedpatients/<int:patientdevice_id>/records/<str:date>/vitalrecords', views.assignedpatientrecordsvitalrecords, name='assignedpatientrecordsvitalrecords'),
    path('listofusers/<int:user_id>/edituser/', views.edituser, name='edituser'),
    path('ajax/validate_username/', views.validate_username, name='validate_username'),
    path('ajax/search_user/', views.search_user, name='search_user'),
    path('ajax/add_device/', views.add_device, name='add_device'),
    path('ajax/get_patients/', views.get_patients, name='get_patients'),
    path('ajax/search_patients/', views.search_patients, name='search_patients'),
    path('ajax/set_patient_to_device/', views.set_patient_to_device, name='set_patient_to_device'),
    path('ajax/get_user_details/', views.get_user_details, name='get_user_details'),
    path('ajax/stop_recording/', views.stop_recording, name='stop_recording'),
    path('ajax/set_recording_duration/', views.set_recording_duration, name='set_recording_duration'),
    path('ajax/unassign_patient/', views.unassign_patient, name='unassign_patient'),
    path('ajax/get_records/', views.get_records, name='get_records'),
    path('ajax/check_device_status/', views.check_device_status, name='check_device_status'),
    path('ajax/get_ecg_batch/', views.get_ecg_batch, name='get_ecg_batch'),
    path('ajax/update_patient_restrictions/', views.update_patient_restrictions, name='update_patient_restrictions'),
    path('ajax/update_user_account/', views.update_user_account, name='update_user_account'),
    path('value/', views.val_func, name='val_func'),
]

